{
  "name": "babel-plugin-try-catch-wrapper",
  "version": "0.1.1",
  "description": "wrap all code in try-catch for reporting js runtime error",
  "main": "lib/index.js",
  "files": [
    "lib/"
  ],
  "scripts": {
    "prepublish": "babel src -d lib",
    "dev": "babel src -d lib -w"
  },
  "author": "syszhpe@gmail.com",
  "license": "MIT",
  "dependencies": {
    "babel-core": "^6.4.5",
    "babel-helper-function-name": "^6.5.0",
    "babel-template": "^6.3.13",
    "babel-types": "^6.7.0"
  },
  "devDependencies": {
    "babel-cli": "^6.4.5",
    "babel-helper-plugin-test-runner": "^6.5.0",
    "babel-loader": "^6.4.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-strict-mode": "^6.5.2",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-es2015-loose": "^7.0.0",
    "babel-preset-node6": "^11.0.0",
    "babel-preset-react": "^6.23.0",
    "babel-preset-stage-0": "^6.5.0",
    "mocha": "^2.4.5",
    "webpack": "^1.2.0",
    "webpack-node-externals": "^1.5.4"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/foio/babel-plugin-try-catch-wrapper"
  },
  "keywords": [
    "report error",
    "runtime error",
    "try-catch wrapper"
  ]
}
